### ISSUE TITLE
ember-animated should support to control the progress of the animation

### ISSUE THREAD

**Issue by Cryrivers** [ember-animation/ember-animated#1]
Honestly I'm not sure about how difficult it would be. But if we'd like to have something like iOS's swipe back gesture to go back (or forth), or 3D Touch interactions like peek and pop, we need the ability to control the progress of the animation based on some variable, ideally a percentage. So in the cases above-mentioned, we can calculate a percentage based on touch movement / force, to make our animation look more native and responsive.

Really appreciated if there are any feedbacks and/or discussions about it. Hopefully we could find a way to nail this.

**Comment by ef4** [comment]
Agreed. I believe this can already be supported with the architecture we have. You could define a Motion that tracks touchmove.

Including a demo of this kind of behavior is on my TODO list for this library.

**Comment by Cryrivers** [comment]
@ef4 great thanks. i'll explore on the `Motion` stuff, which is really exciting to me. 😼

**Comment by ef4** [comment]
Thanks, glad you're interested. I am excited for this work too. I think it's a very solid foundation. Just needs some additional time and attention to get it all usable as a released library.
