### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by samselikoff** [ember-animation/ember-animated#110]
I wanted to create an issue template with a link to a [Twiddle Boilerplate](https://ember-twiddle.com/d83c87fb8a7bdfa5a55b9a3c2bb4c2e5?openFiles=templates.application.hbs%2C) I setup but [the new issue template workflow](https://help.github.com/en/articles/creating-issue-templates-for-your-repository) is configured under a repo's Settings rather than just by making an ISSUE_TEMPLATE.md file in root.

I don't see settings and I think its because I'm neither an admin nor a member of [the `ember-animation`](https://github.com/ember-animation) org. Could I get an invite to the org?

**Comment by ef4** [comment]
Try now.

![With Great Power](https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fdavidmmasters.com%2Fwp-content%2Fuploads%2F2016%2F07%2Fwith-great-power-comes-great-responsibility-spider-man-super-powers-abilities-voltaire-quote.jpg&f=1)

**Comment by samselikoff** [comment]
51a2e58212beab404ccc47e48f2dc77fbdd48f74 closes

**Comment by samselikoff** [comment]
🤝I will not disappoint you!!
