### ISSUE TITLE
Looping animations

### ISSUE THREAD

**Issue by samselikoff** [ember-animation/ember-animated#133]
Wondering if there's a notion of a looping animation with Ember Animated, for example putting an "app screen" into a "wiggle state", similar to how iOS does it when you longTap an app icon to rearrange/delete?

**Comment by ef4** [comment]
I would suggest first trying to use CSS keyframe animation for steady-state, looping animations. It's actually quite good at that, whereas it's not good at animations across DOM mutations, which is what ember-animated is good at.

The one reason we might want to add looping would be if it's hard to compose a steady state CSS animation (wiggling icons) with data-dependent animations (like actually reordering some of the icons while jiggling). I'm not sure if it's hard or not.

**Comment by samselikoff** [comment]
Good call, will give it a shot 👍
