### ISSUE TITLE
Easing of `removedSprites` becoming disassociated from `insertedSprites`

### ISSUE THREAD

**Issue by KeithKosh** [ember-animation/ember-animated#141]
![ember-animated-easing](https://user-images.githubusercontent.com/13221812/61248618-afaa4e00-a710-11e9-86c0-344e43a9f268.gif)

I'm building a sliding page carousel that uses the `move` motion, along with custom `startAtPixel/endAtPixel` values, to slide PNG pages left and right inside a container when navigating forward or back. It works great with one animation at a time, but if the animation is partway through and another navigate is triggered, the easing becomes disassociated. The `removedSprites` appear to inherit the easing value they were in the midst of using - so they keep their ramped-up speed, and just move farther due to the `endAtPixel` being updated - but the `insertedSprites` ease as though just beginning an animation for the very first time. So a gap ends up appearing between the two on-screen elements, even though all on-screen sprites are correctly animating from the proper X values and to the proper X values. The gap disappears when the `insertedSprites` have finished animating, once the end of the ease has caught up.

I'm guessing this is a case where I should be using the `follow` motion so that the existing easing progress can be inherited by the newly inserted element? WIthout documentation I'm having a hard time implementing this, however, as I can't seem to figure out what needs to be passed in as a `source` to `follow`. Am I on the right track here?

**Comment by KeithKosh** [comment]
Just an update: I was able to resolve this issue after digging around a bit in the addon code. It turns out `follow` is used in `move-over` by passing in a `new Move()` instance:

https://github.com/ember-animation/ember-animated/blob/master/addon/transitions/move-over.js#L81-L84

Using this approach for the `insertedSprite`, I was able to get the new page to successfully follow the in-progress easing of the `removedSprites` pages.

👍

**Comment by ef4** [comment]
Glad you were able to figure this out. We do certainly still need more docs here.
