### ISSUE TITLE
Quest: Documentation Site

### ISSUE THREAD

**Issue by ef4** [ember-animation/ember-animated#15]
It's time for docs. Most likely we should use https://ember-learn.github.io/ember-cli-addon-docs/

Sources for learning how things work:

 - [My EmberConf demo](https://github.com/ef4/living-animation)
 - The development & testing demos within the dummy app in this repo
 - the test suite

The following is a burndown list of things that need to be described:

# The Animator Components

 - [ ] animated-each
 - [ ] animated-value
 - [ ] animated-if

# The Support Components

 - [ ] animated-container
 - [ ] animated-orphans
 - [ ] animated-beacon

# Common options on all animator components

 - [ ] key
 - [ ] use
 - [ ] rules
 - [ ] duration
 - [ ] group
 - [ ] initialInsertion
 - [ ] finalRemoval

# The Transition Context
 - [ ] insertedSprites
 - [ ] removedSprites
 - [ ] keptSprites
 - [ ] receivedSprites
 - [ ] sentSprites
 - [ ] duration

# Sprite API

Many of these already have comments in the code.

 - [ ] initialBounds
 - [ ] finalBounds
 - [ ] absoluteInitialBounds
 - [ ] absoluteFinalBounds
 - [ ] initialComputedStyle
 - [ ] finalComputedStyle
 - [ ] getInitialDimension
 - [ ] getFinalDimension
 - [ ] initialCumulativeTransform
 - [ ] finalCumulativeTransform
 - [ ] originalInitialBounds
 - [ ] originalFinalBounds
 - [ ] different
 - [ ] element
 - [ ] transform
 - [ ] revealed
 - [ ] hide
 - [ ] reveal
 - [ ] applyStyles
 - [ ] translate
 - [ ] scale
 - [ ] startAtSprite
 - [ ] startAtPixel
 - [ ] endAtSprite
 - [ ] endAtPixel
 - [ ] endRelativeTo

# Build In Transitions

 - [ ] fade
 - [ ] moveOver (toLeft, toRight, toUp, toDown)

# Built In Motions

 - [ ] adjustColor
 - [ ] adjustCSS
 - [ ] compensateForScale
 - [ ] follow
 - [ ] moveSVG
 - [ ] move
 - [ ] opacity
 - [ ] resize
 - [ ] scale

# How to Author Motions

This you can mostly learn from looking at the nine existing examples. The public API for Motion authors is to implement:

 - [ ] constructor (optional)
 - [ ] interrupted (optional)
 - [ ] animate (mandatory)

**Comment by Oreoz** [comment]
@ef4 I have a documentation site (using `ember-cli-addon-docs`) skeleton working on my fork. Only caveat is I currently have a single test failure, I might require assistance to get it passing. My hunch is that it's failing because of the new style changes that `ember-cli-addon-docs` caused in the dummy application.

Do you want me to PR right away -- or should I get this test passing first (I'm currently stuck on it)?

**Comment by ef4** [comment]
Happy to review the PR even with a failing test.

**Comment by jamesarosen** [comment]
@Oreoz if you get a skeleton set up, I'll gladly add one or two early examples.

**Comment by Oreoz** [comment]
@jamesarosen The documentation skeleton that's scaffolded with Addon Docs should now be available on master. 

As a side note, I'm currently taking a stab at JSDoc'ing the Sprite class. I'll put up a WIP PR tonight with what I have so far.

**Comment by knownasilya** [comment]
Would be nice to have the docs live and the url documented here to see the progress and for those that can make small tweaks but not necessarily tackle documenting a whole API section.

**Comment by Oreoz** [comment]
@ef4 The guys over at `ember-cli-addon-docs` were open to the idea of sorting private, public and deprecated APIs when I connected with them over Slack. But they're currently re-designing the docs website and advised me to hold off for now.

So I filed an issue in order to get this done in the future.

Reference: https://github.com/ember-learn/ember-cli-addon-docs/issues/121

**Comment by ddoria921** [comment]
Is there a version of the docs that is live somewhere? Like @knownasilya said, it would be nice to see and contribute to incremental progress that is visible.

**Comment by edeis53** [comment]
@ddoria921 @knownasilya I've located the docs in progress. They are being created via using the ember-cli-addon-docs addon.

Serve the dummy app in tests and you can view what documentation has been created as commits are made.
http://localhost:4200/docs/api/components/animated-if

**Comment by ef4** [comment]
Oh, I should have mentioned sooner on this thread, but in the last week or so we got them deployed: https://ember-animation.github.io/ember-animated/

**Comment by ef4** [comment]
I'm closing this because we do have docs now, and we should open individual issues for places where there are still gaps.
