### ISSUE TITLE
How to animate a list that overflows and has a max height?

### ISSUE THREAD

**Issue by LuisAverhoff** [ember-animation/ember-animated#152]
So I have a list that plays the following animation based on this custom transition.

```
function* listTransition({ insertedSprites, keptSprites, removedSprites }) {
  for (let sprite of keptSprites) {
    move(sprite);
  }

  for (let sprite of insertedSprites) {
    fadeIn(sprite);
  }

  for (let sprite of removedSprites) {
    fadeOut(sprite);
  }
}
```

This is how the template of my list looks like.

```
<AnimatedContainer class="files-container">
  <ul class="list-group files-list">
    {{#animated-each files use=transition duration=750 as |file|}}
      {{bhsf-fileitem file=file}}
    {{/animated-each}}
  </ul>
</AnimatedContainer>
{{yield}}
```

and here is the css that is used in the template.

```
.files-container {
  max-height: 200px;
  margin-bottom: 10px;
  overflow-y: scroll;

  .files-list {
    display: flex;
    flex-direction: column-reverse;
    -webkit-overflow-scrolling: touch;
  }
}
```

The problem that I'm having is that the scrollbar flickers when new items are added to the list
and the list has not reached its max height. Previously the `<AnimatedContainer>` did not have the `.files-container` class (this was initially placed in the `<ul>` tag)but it was necessary for me to add the class because it was not respecting the fact that the list had a `max-height`(it went pass 200px as it was animating and went back to 200px once it was done) and that it overflows. Is there another way you recommend for me to do this?

**Comment by ef4** [comment]
I think your solution is pretty good and I'm not sure there's a better one.

But one thing you can do if you want to is make your `<ul>` *be* the animated container. As long as you're on the latest version of ember-animated you can pass the `@tag=` argument to make the AnimatedContainer be a `<ul>`:

```hbs
<AnimatedContainer @tag="ul" class="files-container list-group files-list">
  {{#animated-each files use=transition duration=750 as |file|}}
    {{bhsf-fileitem file=file}}
  {{/animated-each}}
</AnimatedContainer>
```

This can help avoid the need to change your markup and CSS just to get things to animate properly.

**Comment by LuisAverhoff** [comment]
Thanks for the response @ef4. Will try it out.
