### ISSUE TITLE
Add a configuration option to only include components that are being used.

### ISSUE THREAD

**Issue by LuisAverhoff** [ember-animation/ember-animated#161]
I would like to see an option to tree shake any module in the ember-animated that was not use. Maybe you can look at how `ember-bootstrap` did it and offer a similar option. They have a `blacklist` and `whitelist` option that can placed in the `ember-cli-build.js` file. The `whitelist` option only includes the components specified and `blacklist` would removes all items specified. Only one of them should be specified in the file.

It would look something like this:

```
module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    'ember-animated': {
      whitelist: ['animated-if', 'animated-each', 'animated-container']
    }
  });

  return app.toTree();
};
```

Don't know if this would be possible(or even if it should be done)so I definitely would like to hear from you. Thanks and great job on this addon. :)

**Comment by ef4** [comment]
This isn't a feature that belongs in ember-animated, it belongs in ember-cli itself which is [why I am implementing that](https://github.com/embroider-build/embroider).

But yes, I have already tested that embroider does what you describe for ember-animated.  You'll only get the components, transitions, motions, and easing functions that you actually use.

**Comment by LuisAverhoff** [comment]
@ef4 Thanks so much for the quick reply and for letting me know. I'll be closing this issue now.

**Comment by ef4** [comment]
We are testing it in several big apps but it is definitely not stable yet. Mostly that depends on getting some more community attention, which is currently all on getting Octane fully released, polished, and documented. As that work winds down (and Octane will be stable in Ember 3.14, which is quite soon), Embroider becomes the next major focus.
