### ISSUE TITLE
Allow animated-each to accept an else clause

### ISSUE THREAD

**Issue by Allerby** [ember-animation/ember-animated#164]
**Describe the bug**
In the documentation it described animated-each as a drop in replacement for the each helper, however I find that it doesn't allow me to write an else condition as the standard helper does.

**To Reproduce**
Use ember animated to print an enumerable using the animated-each helper. In the following example if the list was empty, I would expect it to show "Something else" as would the standard template helper.

```hbs
{{#animated-each listOfThings as |thing|}}
  {{thing}}
{{else}}
  <p>Something else</p>
{{/animated-each}}
```

**Comment by LuisAverhoff** [comment]
Yes, this is something that I would like to see be added to this library as often times I need to something like this when using `animated-each`:

```
{{#if someCondition}}
  {{#animated-value noResultMessage use=transition duration=350 as |message|}}
    <p>{{message}}</p>
  {{/animated-value}}
{{else}}
  {#animated-each listOfThings use=transition duration=350 as |thing|}}
    <p>{{thing}}</p>
  {{/animated-each}}
{{/if}}

Just so that it properly shows one or the other. This would look much more elegant if `animated-each` was able to go to the else condition when no items were available.

**Comment by ef4** [comment]
Yes, this is a good idea. And I think it’s probably pretty easy to
implement. If somebody wants to try it, find the regular `each` inside
animated-each’s template and give it an else block with `{{yield
to=“inverse”}}`.
