### ISSUE TITLE
How to animate height and opacity of an element when inserted?

### ISSUE THREAD

**Issue by st-h** [ember-animation/ember-animated#165]
I am trying to add an element to the page using `animated-if`.

something like:
```
<AnimatedContainer>
  {{#animated-if _showItem use=transition duration=2000}}
    <section class="animated-box">
      <div>Hello, I would like to be animated</div>
    </section>
  {{/animated-if}}
</AnimatedContainer>
```

When the element is added to the page, I would like to have it start with height of 0 and expand to its full height. The following transition seems to sort of do that, however it hides the sprite until the transition is complete. So, creating the space for the element is animated, and when that is done, suddenly the element appears out of nowhere.

```
transition: function *({ insertedSprites, keptSprites, removedSprites }) {
    for (let sprite of insertedSprites) {
      sprite.reveal();
      sprite.startTranslatedBy(0, 0);
      sprite.scale(0, 1);
      scale(sprite);
    }
...
```

Now, I tried to change the insertedSprites to:
```
      sprite.startTranslatedBy(0, 0);
      sprite.scale(2, 2);
      scale(sprite);
```
But now it just instantly displays the sprite at twice its size, only to drop down to regular size after the transition duration. So, I guess I just must be doing something fundamentally wrong. Unfortunately I was unable to find an example for such type of animation using ember-animated.

Additionally I would like to have the element change its opacity from 0 to 1 while being inserted. However, I think I could not get this to work, as the scale animation prevents the element from being seen.

**Comment by ef4** [comment]
Making space for the new sprite is handled by `<AnimatedContainer>`. Since it already does the growing/shrinking, you can give it `overflow: hidden` and that may be all you need to get the look you want without changing the size of the contents.

```hbs
<AnimatedContainer style="overflow: hidden">
  {{#animated-if this.showThing use=this.transition}}
    <section>
      <div>Hello, I would like to be animated</div>
    </section>
  {{/animated-if}}
</AnimatedContainer>
```

```js
import opacity from 'ember-animated/motions/opacity';

export default Controller.extend({

  * transition({ insertedSprites, removedSprites }) {
    for (let sprite of insertedSprites) {
      opacity(sprite, { from: 0 });
    }
    for (let sprite of removedSprites) {
      opacity(sprite, { to: 0 });
    }
  },
});
```

**Comment by st-h** [comment]
@ef4 Ah, Thanks a lot. Now I can see the element finally being animated 👍
