### ISSUE TITLE
Interested in TypeScript?

### ISSUE THREAD

**Issue by simply-alliv** [ember-animation/ember-animated#172]
Hello! I use your addon and really appreciate it. I’m also participating in [this quest issue to add TypeScript support throughout the Ember.js ecosystem](https://github.com/typed-ember/ember-typings/issues/14). This will benefit to *everyone* who uses your addon, not just TypeScript users! (See [here]( improving-developer-experience-for-all-emberjs-users) for an explanation.)

Are you interested in either converting the addon to use TypeScript itself, or in a in adding type definitions? I’d love to help out, if so! And if not, that’s just fine. Thanks!

**Comment by nickschot** [comment]
@AlliVil some more info in here: https://github.com/ember-animation/ember-animated/issues/89 doesn't seem much has happened in that area. The branch is still there though.

**Comment by AlliVil** [comment]
I see, I'll contribute on that branch.

**Comment by AlliVil** [comment]
Should I just add type declaration files or convert JavaScript files to TypeScript files?

**Comment by AlliVil** [comment]
The branch seems to be really old with many outdated/deprecated dependencies. Would it not be better to start a new branch?

**Comment by ef4** [comment]
> Would it not be better to start a new branch?

Whichever you prefer.

> Should I just add type declaration files or convert JavaScript files to TypeScript files?

Convert to typescript. I am opposed to maintaining separate d.ts files because it's so error prone.

**Comment by HeroicEric** [comment]
I think this can be closed now since https://github.com/ember-animation/ember-animated/pull/430 converted to typescript
