### ISSUE TITLE
CSS position is forced to be "absolute" or "fixed" on animating element

### ISSUE THREAD

**Issue by emattias** [ember-animation/ember-animated#176]
**Describe the bug**
I want to animate a divs height that should push down everything after it. By default ember-animated [hard-codes](https://github.com/ember-animation/ember-animated/blob/master/addon/-private/sprite.ts#L655-L660) the `position` css property to be `absolute` or `fixed` which makes everything not be pushed down. Weirdly enough the animation of `AnimatedContainer` doesnt force `position` property. I've made a [twiddle](https://ember-twiddle.com/b29ffde8baa1c22162ce1364271dbe80?openFiles=templates.application.hbs%2C) to show this.

**To Reproduce**
As part of your reproduction, please fork the Ember Animated Boilerplate Twiddle then list the steps for the behavior.

1. Visit my Twiddle: https://ember-twiddle.com/b29ffde8baa1c22162ce1364271dbe80?openFiles=templates.application.hbs%2C
2. Click on `Without AnimatedContainer`
3. See that during that animation the animated element **is not** pushing down the elements after it.
4. Click on `Without AnimatedContainer (with fix)`
5. See that during that animation the animated element **is** pushing down the elements after it.
4. Click on `With AnimatedContainer`
5. See that during that animation the animated element **is** pushing down the elements after it.

**Expected behavior**
I expected the 'Without AnimatedContainer' solution to work. But because `position` is hard coded to be `absolute` (or `fixed`), see:

https://github.com/ember-animation/ember-animated/blob/master/addon/-private/sprite.ts#L655-L660

**Question**
How would you achieve building top bar pushing everything down without forcing the `position` of the animated element to be `static !important` or `relative !important`.

I guess the rationale for forcing the position to be either `absolute` or `fixed` is for performance?

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 78.0.3904.70

**Comment by ef4** [comment]
The whole point of `AnimatedContainer` is to get the behavior you want. It manages the boundary between things that are animating and things that are statically positioned. It also lets you customize 100% of its actual markup, so there's no reason not to pick an existing div that represents your toolbar and just make it be the `AnimatedContainer`.

As for why all other sprites get absolute positioning: it allows animations to be robust even as you add other animations around them or interrupt them with changed content. Statically positioned elements will necessarily make discontinuous jumps as the DOM around them mutates. Our absolutely positioned elements can avoid those jumps by always having their position entirely controlled by the animation system. 

While there are some simple scenarios that don't necessarily need absolute positioning, those scenarios also tend to be so simple that you can just use CSS transitions or keyframe animations directly, which is an encouraged thing to do. (ember-animated is needed when you're reacting to arbitrary content changing. It's not needed to animate a handful of CSS properties in an otherwise static DOM.)

**Comment by ef4** [comment]
By default its duration is always driven by the animator components inside it. In your examples, you can set `duration` on the `animated-if` and the `AnimatedContainer` will match that.

To get more control, you can pass `motion` to `AnimatedContainer`. `motion` defaults to `Resize`, but you can extend `Resize` to behave differently.

```js
import { Resize } from 'ember-animated/motions/resize';
import linear from 'ember-animated/easings/linear';

class CustomResize extends Resize {
  constructor(sprite, opts) { 
    opts.easing = linear;
    opts.duration = 1000;
    super(sprite, opts);
  }
}

class extends Component {
  CustomResize;
}
```

```hbs
<AnimatedContainer @motion={{CustomResize}} />
```

It would be convenient if we added an option on `AnimatedContainer` that lets you customize only the options passed to `Resize` without needing to extend it. That would be a fine PR. It could be named `motionOptions`.

**Comment by emattias** [comment]
Ok, cool! I do more stuff than resize. Can this be done using `AnimatedContainer` also? 

I am talking about the `adjustColor` and the `set(this, 'isOnlineAgain', true);` and `yield wait(1000)`

```js
export default Component.extend({
  init() {
    this._super(...arguments);

    this.transition = this.transition.bind(this);
  },

  ...

  *transition({ insertedSprites, removedSprites, beacons }) {
    for (let sprite of removedSprites) {
      yield adjustColor('background-color', sprite, {
        to: '#f43f85',
      });

      set(this, 'isOnlineAgain', true);

      yield wait(1000);
      sprite.endAtSprite(beacons.one);
      yield resize(sprite);
      set(this, 'isOnlineAgain', false);
    }
  },
});
```

**Comment by ef4** [comment]
Yes, I think resize and adjustColor should be OK directly on an AnimatedContainer. The thing that's probably not OK is `move` (that's when you'd want to do a more typical pattern of using the AnimatedContainer only to hold the place of the thing inside it that's moving).

One other point: using `set` inside the transition like this is probably going to lead to bugs. For one thing, transitions can get interrupted and never finish, so you can end up stuck. For another, using `set` inside a transition can sometimes cause the animation to interrupt itself (if some animator is observing the effects of the set), which is usually not intended.

A better solution here is to have a separate ember-concurrency task for setting `isOnlineAgain`, waiting, and clearing it. And then have an animator component react to `isOnlineAgain`. Basically, think about separating the state from the animation, and make the animation just follow along with the state, without altering it.
