### ISSUE TITLE
DOMRect Doesn't Exist in MS Edge

### ISSUE THREAD

**Issue by nbibler** [ember-animation/ember-animated#191]
Microsoft Edge does not implement `DOMRect`, instead it uses a non-standard [`ClientRect`](https://caniuse.com/#feat=mdn-api_domrect) name for the same object. The same is true for Internet Explorer 11.

These objects are used throughout the `bounds` logic, for example:

https://github.com/ember-animation/ember-animated/blob/728fce7bab70b9771c0ddf410b9f1f55bc701496/addon/-private/bounds.ts#L18

This may be somewhat related to #128.

**Comment by ef4** [comment]
Thanks for reporting.

We can polyfill DOMRect without much code. It doesn't do much.

**Comment by geoffreyd** [comment]
Is this still an issue now that Edge is Chromium based? (as of 2020-01-15)

**Comment by cah-briangantzler** [comment]
I can confirm this breaks IE11 which I sadly still have to support. Moving back to 0.9.0 works. Have to lock this at that version until this is worked out

A polyfill would be nice so I can keep getting updates.

**Comment by lukemelia** [comment]
Polyfill has been added in #204 (released in v0.10.1)
