### ISSUE TITLE
Easings that overshoot end position dont overshoot

### ISSUE THREAD

**Issue by emattias** [ember-animation/ember-animated#198]
**Describe the bug**
The animation stops at end position even with easings that overshoots it.

**To Reproduce**
Use this `easeInOutElastic` easing (from [easings.net](https://easings.net/en#easeInOutElastic), see code [here](https://github.com/ai/easings.net/blob/master/src/easings/easingsFunctions.ts#L124-L132)):

```js
const easeInOutElastic = x => {
  return x === 0
    ? 0
    : x === 1
    ? 1
    : x < 0.5
    ? -(
        Math.pow(2, 20 * x - 10) *
        Math.sin(((20 * x - 11.125) * (2 * Math.PI)) / 4.5)
      ) / 2
    : (Math.pow(2, -20 * x + 10) *
        Math.sin(((20 * x - 11.125) * (2 * Math.PI)) / 4.5)) /
        2 +
      1;
};
```

with move motion:

```js
  transition*({ insertedSprites }) {
    for (let sprite of insertedSprites) {
      sprite.startTranslatedBy(0, 12);
      move(sprite, { duration: 3000, easing: easeInOutElastic });
    }
  };
```

**Expected behavior**
For the animated element to animate like it does in [easings.net](https://easings.net/en#easeInOutElastic) where it overshoots the end position instead of stopping the first time it reaches the end position.

**Screenshots**
![image](https://i.imgur.com/JJxHLCh.gif)

**Comment by jembezmamy** [comment]
I'm trying to do a similar thing. It seems that easing functions are not allowed to overshoot at all:

https://github.com/ember-animation/ember-animated/blob/0c9510b321295a788c56704eae3608bea8cd4b28/addon/-private/tween.ts#L121

What's interesting, values below 0 are allowed... I don't really understand the purpose of this limitation. Maybe it could be removed? That would be great, I'd love to use these bouncy motions. 😄

**Comment by arthur5005** [comment]
Yeah, I forked this repo and tried removing the the `Math.min` restriction when I was trying to implement a spring easing function, seemed to work just fine for my use case, but I have no idea how this might affect other edge cases.

**Comment by ef4** [comment]
I agree we can lift this restriction, it was just unnecessarily defensive. If somebody wants to make a PR that would be great.
