### ISSUE TITLE
Beacon in component used multiple times - access to `this` in transition generator function

### ISSUE THREAD

**Issue by havremunken** [ember-animation/ember-animated#222]
Hi there, I am pretty new at this so if my whole issue is just caused by my ignorance, I am sorry!

I have a flyout menu component, and when clicked, I used ember-animated to animate it on screen. It is ok the way it is (move+fade animation), but I would truly like to scale it from the point of the clicked menu item. This would, as I understand it, require a beacon.

I add a beacon, and the animation works. I get an error about duplicate beacon names, even if I have only the single one, but it works. However, since this flyout menu component will have 3-5 instances in my app, I need unique names for the beacons. So I made a computed property for this, and that also works, in the sense that the beacon gets the expected name, and in my transition generator function, the `beacons` property contains the expected subobjects.

However, in my function, `this` is `undefined` - so I can't access the component computed property to see which beacon I should attach the animation to. 

Is there a better way to handle this situation than my current plan as described? Or is this actually a valid argument for requesting that the transition generator functions be bound so that `this` is actually set to the component the function lives in? I do see that components are not the only place to put animated objects, so this probably needs thought from someone with a much better understanding of this than me.

Thanks for any insights!

**Comment by ef4** [comment]
Hi, it sounds like you are on the right track.

You can bind the transition functions so they will have a `this` if you want them to. This is just one of the annyoing things about javascript. If you're using native classes I like [bind-decorator](https://github.com/NoHomey/bind-decorator) for this.

**Comment by havremunken** [comment]
That worked like a charm, thank you! I still get the error about duplicate beacon names, I'll look at that some more and open a separate issue if I can't figure it out. Thanks for the suggestion!
