### ISSUE TITLE
Uncaught (in promise) Error: Unimplemented

### ISSUE THREAD

**Issue by MichalBryxi** [ember-animation/ember-animated#245]
**Describe the bug**
Using quite simple `{{#animated-value}}` and randomly getting following error in console:

```
move-over.js:80 Uncaught (in promise) Error: Unimplemented
    at moveOver (move-over.js:80)
    at moveOver.next (<anonymous>)
    at runToCompletion (transition-context.js:15)
    at runToCompletion.next (<anonymous>)
    at AnimatedEach.<anonymous> (animated-each.js:237)
    at Generator.next (<anonymous>)
    at ember-scheduler.js:256
    at Backburner._run (backburner.js:1013)
    at Backburner._join (backburner.js:989)
    at Backburner.join (backburner.js:760)
```

**To Reproduce**
Reproduced on this simple demo here: https://gitlab.com/michal.bryxi-bugreport/ember-animated-bugreport

1. Clone the repo, `yarn; yarn start`
2. GOTO: http://localhost:4200/
3. Start wildly clicking on `up` and `down` in random order
4. At one point the error pasted above appears

**Expected behavior**
No error in console appears

**Screenshots**
![ember-animated-bugreport](https://user-images.githubusercontent.com/847473/98289044-e6f8da00-1fa7-11eb-9cc0-828c550bc0a3.gif)

**Desktop (please complete the following information):**
 - OS: OSX Catalina 10.15.6
 - Browser Chrome
 - Version 86.0.4240.111 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Benkooo** [comment]
Any update regarding this error?

**Comment by MichalBryxi** [comment]
I think this can be closed. I just [tried to update following packages](https://gitlab.com/michal-bryxi/bugreport/ember-animated-bugreport/-/merge_requests/2#7030d0b2f71b999ff89a343de08c414af32fc93a) to following versions and it stopped being an issue. Can't pin-point precise version of package(s) where this is fixed, but this should do:

- ember-animated >= 1.0.4
- ember-auto-import >= 2.x
- ember-source >= v3.28.5

**Comment by Benkooo** [comment]
I got the last version of all those packages and it doesn't seem to be the solution..
But I will try another way.
