### ISSUE TITLE
[DOCS] Initial homepage for ember-animated has too much whitespace between lines

### ISSUE THREAD

**Issue by acorncom** [ember-animation/ember-animated#254]
**Describe the bug**
When looking at the Ember animated homepage (https://ember-animation.github.io/ember-animated/) I see far more whitespace between each code line than I'm expecting to see

**To Reproduce**
1. Visit https://ember-animation.github.io/ember-animated/
2. Look at each code block section on the home page
3. You should see multiple blank lines between each actual line of code we care to see

**Expected behavior**
I would expect to not see as much whitespace on the homepage. This used to be the case, but it looks like we now handle whitespace differently than before.

**Screenshots**

Expected:
![image](https://user-images.githubusercontent.com/802505/112759772-34c8ba00-8ffd-11eb-8d6a-3202e8366011.png)

Actual
![image](https://user-images.githubusercontent.com/802505/112759623-8290f280-8ffc-11eb-8fc3-eab12783f347.png)

**Desktop:**
 - OS: Mac OS
 - Browser: Safari 13, Brave 1.21

**Smartphone:**
 - Device: iPhone 8
 - OS: iOS 14.4
 - Browser: Stock Safari

**Additional context**
Looks to be whitespace issues within the `<pre>` tag. Not sure if code blocks didn't use to be rendered in `<pre>` tags or not?

**Comment by SergeAstapov** [comment]
this was fixed some time ago
