### ISSUE TITLE
Why do we need `assert-never` in `dependencies`?

### ISSUE THREAD

**Issue by esbanarango** [ember-animation/ember-animated#263]
👋 

We're having a weird issue with the latest `ember-auto-import: ^2.0.1`  in production:

```
Could not find module `assert-never` imported from `ember-animated/components/animated-each`
```

But this is a TS package, are we expecting this to be in the production build? 🤔

**Comment by ef4** [comment]
`assert-never` is written in TS, but it has a real runtime implementation too and it publishes to NPM with compiled JS.

Do you mean this only breaks in production, or does it also break in development?

Is ember-animated a direct dependency of your app or do you use it through another addon?

This sounds like a possible bug in ember-auto-import 2.0.

**Comment by esbanarango** [comment]
The issue was actually related with the `integrity` check from `ember-sri`
