### ISSUE TITLE
Need workaround for Ember checkbox's jQuery dependency

### ISSUE THREAD

**Issue by ef4** [ember-animation/ember-animated#31]
This is hopefully an easy one for somebody who wants to contribute.

[This PR](https://github.com/ember-animation/ember-animated/pull/30) disables jQuery, but the tests don't pass because Ember's `{{input type="checkbox"}}` requires jQuery until very recent Ember versions.

Your mission is to change our demos to not use `{{input type="checkbox"}}` and instead just use `<input type="checkbox">` with manual binding of the `checked` attribute and the necessary event.

An easy way to experiment is to check out the branch from the above-mentioned PR, run the dummy app, visit /demos/here-there, and click the checkbox. It throws an exception.

**Comment by cibernox** [comment]
Closed by #32 and/or #33
