### ISSUE TITLE
IE11 / Windows 7 Issue

### ISSUE THREAD

**Issue by chrism** [ember-animation/ember-animated#34]
Testing on IE11 gives me this error in the console.

```bash
SCRIPT5009: 'Symbol' is undefined
File: vendor-8336295e6bef0390b14bd99dbe877138.js, Line: 6682, Column: 133
```

Which looks like it is due to `ember-animated` code

```js
6679 try{for(var s,u=a(e)[Symbol.iterator]();!(n=(s=u.next()).done);n=!0){var l=s.value
6680 if(l.isEmberAnimatedListElement)r=l.get("child.id")
6681 else if(null!=r){var c=this._ancestorObservers.get(l)
6682 c||this._ancestorObservers.set(l,c=new Map),c.set(t,r),r=null}}}catch(e){i=!0,o=e}finally{try{!n&&u.return&&u.return()}finally{if(i)throw o}}return this},unobserveAncestorAnimations:function(e,t){var r=!0,n=!1,i=void 0
'Symbol' is undefined
6683 try{for(var o,s=a(e)[Symbol.iterator]();!(r=(o=s.next()).done);r=!0){var u=o.value,l=this._ancestorObservers.get(u)
```

It would make sense because before adding `ember-animated` the site was working.

Should IE11 be supported? If so, I think this is quite important.

Thanks.

**Comment by chrism** [comment]
An update:

In case anyone else comes across this issue (or is unaware) it can be resolved by including the polyfill as recommended here:
https://github.com/babel/ember-cli-babel/issues/40#issuecomment-300729304 

```js
var app = new EmberApp({
  'ember-cli-babel': {
    includePolyfill: true
  }
});
```

Maybe this should be close now? Hopefully it might help someone else.

**Comment by ef4** [comment]
Thanks for the followup. Yes, I think we can close this. 

The root issue here is that `includePolyfill` doesn't understand your app's `config/targets.js`. There has been [some work](https://github.com/babel/ember-cli-babel/pull/142) on fixing that but it looks like somebody needs to give it more attention.
