### ISSUE TITLE
Question about building image slider

### ISSUE THREAD

**Issue by deepflame** [ember-animation/ember-animated#38]
Hi!

First thanks so much for this awesome library.
I hope here is the right place to ask my question. Please let me know if I should rather do it somewhere else.

I am trying to build an image slider with ember-animated.

1. I use `animated-value` like this for the transition. Would you recommend a different approach?

```handlebars
  {{#animated-container tagName="ul"}}
    {{! preload images }}
    {{#each images as |image|}}
      <li>
        <div style="display:none; background-image: url('{{image}}');"></div>
      </li>
    {{/each}}

    {{#animated-value imageIdx rules=rules duration=1000 as |idx|}}
      <li class="current">
        <div class="pic" style="background-image: url('{{object-at idx images}}');"></div>
      </li>
    {{/animated-value}}
  {{/animated-container}}
```

2. I am trying to transition the images by scaling and changing the opacity (cross dissolve). Changing the opacity is working great, but scaling it in and out is not working as intended. Basically I am trying to recreate the transition here: http://spacialtheme.herokuapp.com/2.6/index-photography.html

	here is my approach, but I get an error in the console. Guess it is not the right way to use `scale`.

```javascript
import { parallel } from 'ember-animated';
import scale from 'ember-animated/motions/scale';
import opacity from 'ember-animated/motions/opacity';

export default function * ({ removedSprites, insertedSprites, keptSprites, duration }) {
  removedSprites.map(s => {
    if (s.revealed) {
      parallel(
        opacity(s, {
          to: 0,
          duration
        }),
        scale(s, {
          from: 1,
          to: 1.2,
          duration
        })
      );
    }
  });

  insertedSprites.concat(keptSprites).map(s =>
    parallel(
      opacity(s, {
        to: 1,
        duration
      }),
      scale(s, {
        from: 0.8,
        to: 1,
        duration
      })
    )
  );
}
```

Any hint or comment is appreciated.

**Comment by deepflame** [comment]
Regarding 2.: Hmm, seems we would need a `startScaledBy` and `endScaledBy` for sprites, right?

**Comment by deepflame** [comment]
Regarding 2:

solved the transition now with a custom 'scaling' motion which is based on the opacity "motion" like this (basically applies a `transform` to the element):

```js
import { Motion, rAF, Tween } from 'ember-animated';
import { easeInAndOut } from 'ember-animated/easings/cosine';

export default function scale(sprite, opts) {
  return new Scale(sprite, opts).run();
}

export class Scale extends Motion {
  constructor(sprite, opts) {
    super(sprite, opts);
    this.prior = null;
    this.tween = null;
  }

  interrupted(motions) {
    this.prior = motions.find(m => m instanceof this.constructor);
  }

  * animate() {
    let { sprite, duration, opts } = this;
    let to = opts.to != null ? opts.to : sprite.finalComputedStyle != null ? parseFloat(sprite.finalComputedStyle.opacity) : 1;
    let from;

    if (this.prior) {
      from = this.prior.tween.currentValue;
      duration = Math.abs(from - to) * duration; // set proportional duration
    } else {
      from = opts.from != null ? opts.from : sprite.initialComputedStyle != null ? parseFloat(sprite.initialComputedStyle.opacity) : 0;
    }

    this.tween = new Tween(from, to, duration, easeInAndOut);

    while (!this.tween.done) {
      sprite.applyStyles({
        transform: `scale(${this.tween.currentValue})`
      });
      yield rAF();
    }
  }
}
```

Would be great to get some implementation feedback if possible and time permits, otherwise you may also close the issue as it seems to work now.

**Comment by deepflame** [comment]
Ok, thanks for taking the time to answer @ef4 . Appreciate it!

I will have a look then at `sentSprites` and `receivedSprites`. May also transition between two lists - one single item list with the image that is shown and a list with the others that are not.

Thanks again. Will close this issue now :)

**Comment by denzo** [comment]
@ef4 I'm struggling to understand how to animate width and height or scale of a sprite 🤔 basically I'm looking for a way to zoom out a removed sprite.

Here's the CSS of what I am trying to achieve.

@keyframes my-transition {
  from {
    transform: translateZ(0);
    opacity: 1;
  }
  to {
    transform: translateZ(-300px);
    opacity: 0.5;
  }
}
