### ISSUE TITLE
Unintentional scale transition occurring during fade

### ISSUE THREAD

**Issue by edeis53** [ember-animation/ember-animated#50]
Trying to perform a fade with animated-if, but getting a unwanted bonus height & width animation too!

Cause appears related to content overflow and the appearance of the scrollbars, which changes the dimensions of the animated container as the content is toggled. For some reason even though I am only requesting a fade transition, it is animating a size change and creating the unwanted effect of moving the content on screen.

![](https://i.imgur.com/yDMygrm.gif)

[Link to: Example with slow duration to better see what is going on](https://i.imgur.com/8rO4MAC.gifv) -- You can see the animated-container width and height being animated in the inspector. The fade transition is used here.

[Twiddle example (slow duration)](https://ember-twiddle.com/f3d13f824bb25da01cc23c1ea2922279?openFiles=templates.application.hbs%2C) -- Make sure to reduce your window size so that when the menu is shown, it has to scroll. 

Thought maybe it was an issue with the transition type. But the animation of animated-container occurs even if I used an empty transition type, eg:
```
    myTransition: function * ({ insertedSprites, removedSprites }) {

    },

```

The expected behaviour of applying an opacity/fade transition should be that only opacity/fade be animated.

How to prevent the width and height animation of animated-container?

**Comment by ef4** [comment]
It should be sufficient to write your CSS so that the animated-container always has a constant size.

**Comment by edeis53** [comment]
Thanks for the hint @ef4! Poor CSS for the Header resulted in some collapsing of it's element, which resulted in animated-container changing size.
