### ISSUE TITLE
Memory leak in emberAnimatedSingleton

### ISSUE THREAD

**Issue by kevinkucharczyk** [ember-animation/ember-animated#514]
**Describe the bug**
We have a large app with a very large test suite. We've noticed that there are a lot of retainers in heap snapshots after running our tests:
![CleanShot 2022-08-31 at 09 01 40](https://user-images.githubusercontent.com/3127419/187559783-cd77f581-3da4-4a2f-b082-6825d55f19be.png)

When looking at the `emberAnimatedSingleton` object, we can see that the main culprits seem to be the `concurrency-helpers.cancellation`, `ember-scheduler.priv` and `scheduler.microRoutines` keys:
![CleanShot 2022-08-31 at 09 19 14](https://user-images.githubusercontent.com/3127419/187560213-a3b9ccb2-8071-4f6f-b1f3-22f3af528250.png)

The entries in those maps seem to be accessible even after the test suite has finished:
![CleanShot 2022-08-31 at 09 20 34](https://user-images.githubusercontent.com/3127419/187560343-028a4fce-125c-4492-b673-7528b96b6912.png)

Which leads me to believe that there are still references being held to those objects somewhere and they're never being cleaned up.

**To Reproduce**
I've prepared a small showcase Ember project here: 
[ember-animated-memory-leak.zip](https://github.com/ember-animation/ember-animated/files/9457224/ember-animated-memory-leak.zip)

Inside, I click between Route 1 and Route 2 a few times. Each time Route 1 loads - which contains an ember-animated element - the maps in the `ember-scheduler.priv` map keeps growing:
![CleanShot 2022-08-31 at 09 42 53](https://user-images.githubusercontent.com/3127419/187562783-9a7713f7-1468-44c5-97b8-93133154868c.png)

Plus, all the old tasks still retain all of their information:
![CleanShot 2022-08-31 at 09 45 32](https://user-images.githubusercontent.com/3127419/187562809-827a630f-70c2-415b-8c80-7bef36b2be27.png)

**Expected behavior**
I'd expect all references to destroyed elements and tasks to be removed, and those tasks to be garbage collected.

**Comment by ef4** [comment]
I think the WeakMaps are confounding your analysis. The devtools don't do a good job of conveying what's weird about weak references.

The WeakMaps themselves are supposed to persist, as they are module-scoped state. Their entries will only persist if something else is retaining them. So it's the "something else" that is actually leaking memory.

That might still be something in ember-animated, or it might be something else, but these WeakMap entries are only a symptom, not a cause.

**Comment by ef4** [comment]
I tried running your reproduction. I think it is giving misleading results, because the `console.log(window.emberAnimatedSingleton)` itself is causing the console to retain objects.

If I take the console log out and rely on heap snapshots to count how many Tasks are retained, I can't get the number of retained tasks to increase.

**Comment by kevinkucharczyk** [comment]
I think you're right.

There's definitely something fishy happening in our app because we are seeing those retainers in our test suite, but it may not be coming from ember-animated itself - I wasn't able to reproduce this in a sample app.
Like you said, there's probably something else holding on to references, but it's hard to find the exact source due to the size of our app and all its dependencies.

Thanks for having a look!

**Comment by acorncom** [comment]
@kevinkucharczyk should this issue be closed at this point?

**Comment by kevinkucharczyk** [comment]
@acorncom of course, sorry about that! Closing!

**Comment by acorncom** [comment]
@kevinkucharczyk no need to apologize, I see lots of open issues like this where it's hard to tell if they can be closed or not. Hence the question 😄
