### ISSUE TITLE
Conform to new template lint rules

### ISSUE THREAD

**Issue by ef4** [ember-animation/ember-animated#52]
When I updated to the newest ember-cli, I had to [disable several new template lint rules](https://github.com/ember-animation/ember-animated/blob/2fe4f3646e0147b91248cbf9159d251e94f038cc/.template-lintrc.js#L6-L15).

It is hopefully straightforward to pick one of those rules, re-enable it, and fix the templates to follow the rule.

**Comment by xomaczar** [comment]
Seems like this issue was resolved ^ - can we close it

**Comment by ef4** [comment]
Yes, good call.
