### ISSUE TITLE
Animation Between Routes w/ Loading State

### ISSUE THREAD

**Issue by robaguilera** [ember-animation/ember-animated#58]
If I missed something in the docs I apologize in advance.  What I'm trying to achieve is animating from the loading route to the app once my data is fetched.  The structure of my app is:
```
+ parent/
|
|  + view/
|  + loading/
|  + otherPage/
| template.hbs
```
I'm just a little lost as what to wrap as a `animated-component/if/value` so I can animate between the loading component to any route, or better yet how to animate from one route to any other route.

**Comment by knownasilya** [comment]
@ef4 any idea when this might happen?
