### ISSUE TITLE
Split docs tests and library tests

### ISSUE THREAD

**Issue by ef4** [ember-animation/ember-animated#63]
(cc @cibernox because you said you were working on fixing related issues)

I think it's important that we continue to run the test suite with RAISE_ON_DEPRECATION, so we aren't causing deprecations in consuming apps.

But the tests suite also includes all of ember-cli-addon-docs, which itself pulls in a ton of addons. Quite often some of those trigger deprecation warnings, and it would be better to just accept the warnings until the authors can fix them.

Thus, I want to make it possible to test only our own code using RAISE_ON_DEPRECATION, and test the docs site without RAISE_ON_DEPRECATION. 

We should either split things into two dummy apps, or setup a feature flag around all usage of addon docs so we can do a CI run with the docs removed.

**Comment by cibernox** [comment]
Yeah, not being able to release a new version because of a deprecation being fired on a dependency of a dependency of the documentation page is 😠

**Comment by samselikoff** [comment]
If you could choose, would you rather have the AddonDocs site live in its own `/docs` directory, and use that linking script you wrote to have it pull its deps from `/package.json`?

Or would you rather have a new `test-projects/01-basic-app` that has most of the core tests? (And also allows for us to do things like `test-projects/02-basic-addon` to test an addon that depends on EA).

**Comment by ef4** [comment]
Oh, so this issue can arguably be closed because I already implemented the feature flag solution. But I still think it would be good to also split the docs and test apps.

I think you're asking if it's better to move the docs into a new app or move the tests into a new app. Probably the docs, since they are the one that's likely to need extra dependencies.

I would be happy if the docs site was written explicitly as an ember app that depends on the addon, and has its own entirely self-contained package.json unrelated to anything in the addon. Ideally with yarn workspaces making the use of two separate package.json files more efficient, but that has the unfortunately limitation of not allowing nesting, so we'd need to move the addon's own code into a subdir. Which is tolerable but not great (ember-auto-import is already structured that way).

**Comment by samselikoff** [comment]
Yeah, I think nesting is a big ask for many addons that just want an AddonDocs site. Unfortunate.

If it were its own `/docs` app, how could it depend on the local version of `ember-animated` if it had its own self-contained package.json?

**Comment by samselikoff** [comment]
Closing for now, should probably solve this generally in AddonDocs (and will probably need to soon)
