### ISSUE TITLE
Glint ember-animated/template-registry not found

### ISSUE THREAD

**Issue by deathaz** [ember-animation/ember-animated#643]
**Describe the bug**
After upgrade ember-animated from `1.0.4` to `1.1.1`, and also follow up with apply glint usage changes as of [docs](https://ember-animation.github.io/ember-animated/docs#usage-with-glint), vscode typescript, `tsc --noEmit` or `glint` is reporting error for ember-animated's template registry as below.
```
error TS7016: Could not find a declaration file for module 'ember-animated/template-registry'. '<app name>/node_modules/.pnpm/.../node_modules/ember-animated/dist/template-registry.js' implicitly has an 'any' type.
  There are types at '<app name>/node_modules/ember-animated/declarations/template-registry.d.ts', but this result could not be resolved when respecting package.json "exports". The 'ember-animated' library may need to update its package.json or typings.

7 import type EmberAnimatedRegistry from 'ember-animated/template-registry'
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by deathaz** [comment]
sorry for the duplicate reference, i don't have much experience to use github, just learning on how to contribute with using codespaces.

**Comment by esbanarango** [comment]
Same issue here.
