### ISSUE TITLE
v1.1.3 is missing type declarations

### ISSUE THREAD

**Issue by dfreeman** [ember-animation/ember-animated#681]
The last 1.x release, v1.1.3, seems to be missing its type declarations. This is causing `ember-try` scenarios, which always ignore the lockfile, to fail for our projects with an `ember-animated@^1` dependency unless we lock to `<= 1.1.2`

For instance:
 - v1.1.2: https://unpkg.com/ember-animated@1.1.2/declarations/index.d.ts
 - v1.1.3: https://unpkg.com/ember-animated@1.1.3/declarations/index.d.ts

**Comment by SergeAstapov** [comment]
appears `pnpm exec glint --declaration` was not working at a time of publishing.

Checked out `v1.1.3` tag and appears `pnpm exec glint --declaration` does not create `declarations` folder and I missed that at a time of publishing.

Trying to figure out the reason for this

**Comment by SergeAstapov** [comment]
looks like I facing the same issue as https://github.com/typed-ember/glint/issues/599

**Comment by SergeAstapov** [comment]
published as v1.1.4.

Thank you for pointing this out @dfreeman!

**Comment by dfreeman** [comment]
Thank you!
