### ISSUE TITLE
Tripped up by easing imports

### ISSUE THREAD

**Issue by samselikoff** [ember-animation/ember-animated#71]
This might be silly, but I was trying to use the `linear` ease but kept messing up my imports.

I had this

```js
import { easeOut, easeIn } from 'ember-animated/easings/cosine';
```

and came up and added `linear`:

```js
import { easeOut, easeIn, linear } from 'ember-animated/easings/cosine';
```

I plugged that into my `move` motion but still wasn't seeing it. (Sometimes these are hard to tell just by looking at it). But I was sure it wasn't linear...

I dug into the code and put a breakpoint in the `Tween` class and saw the default of `easeInOut` was still being used.

That's when I realized I was trying to import `linear` from `easings/cosine`. There is a guard about a Tween's `easing` needing to be a function, but this was an undefined import I guess...

So I switched it

```diff
- import { easeOut, easeIn, linear } from 'ember-animated/easings/cosine';
+ import { easeOut, easeIn } from 'ember-animated/easings/cosine';
+ import { linear } from 'ember-animated/easings/linear';
```

...same thing.

I then finally realized `linear` is the default import from `easings/linear`.

```diff
- import { linear } from 'ember-animated/easings/linear';
+ import linear from 'ember-animated/easings/linear';
```

Maybe we could export an index from `ember-animated/easings`? So you can

```js
import { easeOut, easeIn, linear } from 'ember-animated/easings';
```

Also I don't know if this is possible, but if there was some way to warn if users try to pass in an undefined value that would have also been helpful.

**Comment by ef4** [comment]
(It's an ember-cli deficiency that this isn't a static build error. The point of imports is that they are analyzable. In embroider this is a build error, as it should be.)

I agree there is inconsistency here. 

An index has the nicest user experience, my only hesitation is that there's no completely-spec-compliant way to then shake out unused easings. 

Another option is to standardize on always using default exports:

```js
import easeOut from 'ember-animated/easings/ease-out';
import easeIn from 'ember-animated/easings/ease-in';
import linear from 'ember-animated/easings/linear';
```

Or standardize on only named exports:

```js
import { easeOut, easeIn } from 'ember-animated/easings/cosine';
import { linear } from 'ember-animated/easings/linear';
```

**Comment by samselikoff** [comment]
I've heard this before, about the index-with-named-exports not being shakable. How is this possible? Seems like the file is easily analyzable from a human perspective... maybe I'm wrong?

**Comment by ef4** [comment]
Modules can have side effects. It's not good style, but it's valid javascript, so a general purpose packaging tool can't just go and break it.

For example, this code is legal, but if you decided nobody was using `linear` and tried to shake it out, it would break:

```js
// index.js
export { default as linear } from './linear';
export { eastOut, eastIn } from './cosine';
```

```js
// linear.js
window.easingHelper = function() {};
export default function() {
  ...
  easingHelper();
  ...
}
```

```js
// cosine.js
export default function() {
  ...
  easingHelper();
  ...
}
```

(And `window` is not the only hole, it's impossible to statically detect all the ways state can leak.)

Webpack gets around this by allowing packages to declare themselves side-effect free via their package.json. We can choose to respect that, but it's -- in a small but important way -- deviating from the actual Javascript language.

**Comment by samselikoff** [comment]
Ah. That makes sense. Thanks for explaining!

**Comment by samselikoff** [comment]
Is shaking "a thing"? I know it's been talked about for years, but I'm curious if it has an immediate timeline. If not, we could always provide a migration path if/when it gets there.

**Comment by ef4** [comment]
It's already implemented for non-ember-addon packages in ember-auto-import, and it's already implemented for ember packages in embroider.

**Comment by samselikoff** [comment]
closed by https://github.com/ember-animation/ember-animated/issues/90
