### ISSUE TITLE
Sharing easing

### ISSUE THREAD

**Issue by samselikoff** [ember-animation/ember-animated#73]
Duration seems to sometimes be shared automatically, e.g. between AnimatedContainer and an animator component that takes `@durration` arg.

Is it possible to do the same for easing? If I want to use Linear easing on my animator, the Container will now be "out of sync", as it falls back on the default easing of `easeInOut`.

**Comment by ef4** [comment]
I do think it would be reasonable to handle easing similar to how we handle duration.

Each transition and motion would still be free to ignore or adjust it (which is already also true of duration), so we can use it in the places where it makes logical sense and not where it doesn't.
