### ISSUE TITLE
Help thinking through an animation

### ISSUE THREAD

**Issue by samselikoff** [ember-animation/ember-animated#74]
Hi! I was hoping to get some guidance/advice on how best to organize an animation I'm working on.

There's a nice animation from the Things OSX app:

![kapture 2019-03-05 at 18 20 20](https://user-images.githubusercontent.com/2922250/53844362-751af280-3f73-11e9-9ccb-a51a5a9b9546.gif)

What I'm looking to build is similar to this but actually slightly different.

The animation from Things is actually more straightforward to me, because double-clicking a Todo reflows the contents below it, and there's a lot of stuff in Ember Animated to help there.

What I'm looking to do is render something very similar to the "expanded" state, without "pushing" any of the lower items down. Almost like the expanded state is going to be using `position: absolute` to grow & show additional data, but there will still be a placeholder "underneath" to keep the space in the list for the existing items.

I'm having trouble thinking about the best way to go about doing this.

My first thought was to make two different versions of the "card", one collapsed and one expanded. Then, when the user selects an item, really I could just add a `visibility: hidden` class to the collapsed, and show the expanded, and then animate it up. I could start out the expanded sprite at the CSS values for the collapsed version, and use motions to smoothly animate the width and text size up to the expanded version.

This approach feels a little hacky to me though, as I really want to smoothly animate out a card from one state to another. It's the same card, just certain dimensions & contents about it are changing.

So, the other approach I thought was to treat the card as a `keptSprite` and use something like `animated-value`, to animate the card between two different states with like `item.isExpanded`. That would give me one conceptual "card" that exists in two different states.

The problem here is that I'd want a placeholder left behind when `isExpanded` is true, to hold space in the normal document flow for the items below it. I feel like Sprites are perfect for this since they contain info about their height and width. Is there some way I could use a `keptSprite`'s information, render a placeholder to the DOM, and then animate that keptSprite myself to the expanded state, setting absolute positioning on it?

I wanted to write up some thoughts here if anyone has any ideas, but I'd also love to jump on a screen share to explain more.

Thanks!

**Comment by ef4** [comment]
With a setup something like this:

```hbs
{{#each items as |item|}}
  {{#animated-if item.expanded use=transition}}
    <BigVersion @item={{item}} style="position: absolute" />
  {{/animated-if}
  <AnimatedBeacon @name="small-item-{{item.id}}">
    <SmallVersion @item={{item}} />
  </AnimatedBeacon>
{{/each}}
```

I think you can construct a `transition` such that when the BigVersion is entering, it scales itself up from the size of the SmallVersion (which it can detect via the beacon).

The SmallVersion never animates, it's just sitting there in the background. The beacon exists only to emit geometry at the appropriate time so that other transitions can find it.

**Comment by samselikoff** [comment]
Makes sense! I had a similar thought once I got around to learning about beacons.

What about showing/hiding `<SmallVersion>` based on the state of the `animated-if`'s transition? Is there some sort of `animatedEnd`/`animatedEnd` callback that I could use to show/hide `<SmallVersion>`?

**Comment by ef4** [comment]
If you want SmallVersions appearance to change during the animation (even just hiding), it's probably best to make it into a sprite. 

One way is to bring it inside the if:

```hbs
{{#each items as |item|}}
  {{#animated-if item.expanded use=transition}}
    <BigVersion @item={{item}} style="position: absolute" />
    <SmallVersion @item={{item}} />
  {{else}}
    <SmallVersion @item={{item}} />
  {{/animated-if}
{{/each}}
```

Done this way, you will have two insertedSprites to manage when expanding, and you can apply different motions to each.

**Comment by samselikoff** [comment]
Ah, makes sense 👌  Thanks for the tip!

(I'm working on my training now, but really looking forward to rolling this stuff back into the docs. I think a cookbook/examples section would be huge for folks.)

What would be your preferred approach to applying different motions to different Sprites? Differentiate based on some aspect of the Sprite's `element`?

**Comment by ef4** [comment]
Yes, I think looking at the element's is fine.

This kind of use case (heterogeneous sprites inside a single animator) is currently hard to use with animated-orphans because you can't easily correlate them independently. I have ideas to fix that but haven't implemented yet.

**Comment by samselikoff** [comment]
I'm experimenting with [your previous comment](https://github.com/ember-animation/ember-animated/issues/74#issuecomment-471240975) and trying to figure out the best way to identify the correct beacon:

```hbs
{{#each items as |item|}}
  {{#animated-if item.expanded use=transition}}
    <BigVersion @item={{item}} style="position: absolute" />
  {{/animated-if}
  <AnimatedBeacon @name="small-item-{{item.id}}">
    <SmallVersion @item={{item}} />
  </AnimatedBeacon>
{{/each}}
```

In this case, if I'm on `item:id(4)`, how will I know that from within my `transition`, such that I can identify `beacons['small-item-4']`?

**Comment by ef4** [comment]
I think you need to put an attribute on BigVersion's element and use sprite.element.

(That kind of reading is OK, as long as you're only accessing things like data-attrs and classes that don't trigger layout.)
