### ISSUE TITLE
Using Liquid Fire vs. Ember Animated today

### ISSUE THREAD

**Issue by samselikoff** [ember-animation/ember-animated#79]
I know there is a longer-term plan to reimplement Liquid Fire on top of Ember Animated, but for folks working today, could you provide a 2-3 sentence summary of when they should use Liquid Fire (if they at all) vs. Ember Animated?

**Comment by ef4** [comment]
The major thing that remains in liquid-fire (and will stay there) is application-level concerns: having a thing like `app/transitions.js` that controls how your application "in the large" is laid out in space and animates from route to route.

**Comment by xud6** [comment]
> 
> 
> The major thing that remains in liquid-fire (and will stay there) is application-level concerns: having a thing like `app/transitions.js` that controls how your application "in the large" is laid out in space and animates from route to route.

I also have same problem. Do you mean we should use liquid-fire for things like animates from route to route and use Ember Animated for what it can do at same time?
