### ISSUE TITLE
Ember Canary (3.10 - Ember Octane Preview) breaks due to Computed Property Changes.

### ISSUE THREAD

**Issue by geoffreyd** [ember-animation/ember-animated#93]
Changes to the ComputedProperty API mean that ComputedProperty#constructor now takes an array instead of a function: https://github.com/emberjs/ember.js/blob/707a938e536cb921dbe80ee270c431d1b9717e38/packages/@ember/-internals/metal/lib/computed.ts#L168

Which breaks the usage in TaskProperty#constructor: https://github.com/ember-animation/ember-animated/blob/master/addon/-private/ember-scheduler.js#L26

**Comment by ef4** [comment]
Thanks for reporting, marking as a dup of #75.

I think this should be a pretty straightforward fix for a first-time contributor if anyone wants to have a go.
